apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: fiananceme-deployment
spec:
  selector:
    matchLabels:
      app: fiananceme
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: fiananceme
    spec:
      containers:
        - name: fiananceme
          image: amardeepmalale96/fiananceme # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8070 # The port that the container is running on in the cluster


---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: fiananceme-ssvc
spec:
  selector:
    app: fiananceme
  ports:
    - protocol: "TCP"
      port: 8070 # The port that the service is running on in the cluster
      targetPort: 8070 # The port exposed by the service
  type: LoadBalancer # type of the service.
